image: node:10.16.0

pages:
  script:
  - npm install
  - npm install gatsby-cli
  - npm install --save gatsby-plugin-gtag
  - npm audit fix
  - node_modules/.bin/gatsby build
  artifacts:
    paths:
    - public
  cache:
    paths:
      - node_modules
  only:
  - master
